# Generated by Django 4.0.1 on 2022-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('functionality', models.CharField(choices=[('Drivetrain', 'Drivetrain'), ('Braking', 'Braking'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
