# Generated by Django 4.0.1 on 2022-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_component_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='functionality',
            field=models.CharField(choices=[('Drivetrain', 'Drivetrain'), ('Braking', 'Braking'), ('Other', 'Other')], default='Drivetrain', max_length=15),
        ),
    ]
