# Generated by Django 4.0.1 on 2022-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_component_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='components',
            field=models.ManyToManyField(to='main_app.Component'),
        ),
    ]
